name: torch-sim-edith
channels:
  - conda-forge # needed for gcc, edith only has a very old version
  - defaults
dependencies:
  - python=3.13
  - ipython
  - pip
  - gcc # needed for mace-torch
  - gxx # needed for mace-torch
  - pip:
    - ase
    - torch
    - torch-sim-atomistic
    - mace-torch
