[project]
name = "hello-edith"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "globus-compute-sdk>=3.8.0",
    "ipython>=9.3.0",
]
